[[constraint]]
  branch = "master"
  name = "github.com/betabandido/rest-api-perf"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "~4.0.0"

[prune]
  go-tests = true
  unused-packages = true
