[package]
name = "rest_api_common"
version = "0.1.0"
authors = ["Victor Jimenez <betabandido@gmail.com>"]
edition = "2018"

[dependencies]
mongodb = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"