[[constraint]]
  branch = "master"
  name = "github.com/betabandido/rest-api-perf"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "~1.7.0"

[prune]
  go-tests = true
  unused-packages = true
