[package]
name = "rocket_rest_api"
version = "0.1.0"
authors = ["Victor Jimenez <betabandido@gmail.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.8"
rocket = "0.4"
rocket_contrib = "0.4"
rest_api_common = { git = "https://github.com/betabandido/rest-api-perf" }
