[[constraint]]
  branch = "master"
  name = "github.com/betabandido/rest-api-perf"

[[constraint]]
  name = "github.com/gramework/gramework"
  version = "~1.6.0"

[prune]
  go-tests = true
  unused-packages = true
