[[constraint]]
  branch = "master"
  name = "github.com/betabandido/rest-api-perf"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
