[package]
name = "actix_rest_api"
version = "0.1.0"
authors = ["Victor Jimenez <betabandido@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
parking_lot = "0.8"
rest_api_common = { git = "https://github.com/betabandido/rest-api-perf" }
